apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: jha
spec:
  serviceAccountName: jha
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount/token
  volumes:
  - name: nginx-volume
    secret:
      secretName: jha-secret
