apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command:
        - "sleep"
        - "4500"
    - name: gold
      image: redis
      

