apiVersion: v1
kind: Pod
metadata:
  name: orange
spec:
  containers:
    - name: orange-contatiner
      image: busybox:1.28
      command:
        - "sh"
        - "-c"
        - "echo The app is running! && sleep 3600"
  initContainers:
    - name: orange-init-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 20"
