apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
    - name: red
      image: busybox:1.28
  initContainers:
    - name: warm
      image: busybox
      command: ['sh', '-c', 'sleep 20']