apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    name: httpd-frontend
spec:
  selector:
    matchLabels:
      rs: one
  template:
    metadata:
      name: httpd-frontend
      labels:
        rs: one
    spec:
      containers:
        - name: httpd-frontend
          image: nginx
  replicas: 3