apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /tmp/secrets
        name: projected-volume-for-my-serviceaccount
  volumes:
  - name: projected-volume-for-my-serviceaccount
    projected:
      sources:
      - serviceAccountToken:
          path: service-account-token-as-file
          expirationSeconds: 600