apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: pod-reader
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /tmp/secrets
        name: projected-volume-for-service-account-blog
  volumes:
  - name: projected-volume-for-service-account-blog
    projected:
      sources:
      - serviceAccountToken:
          path: service-account-token-as-file
          expirationSeconds: 180