apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: pod-reader
  namespace: default # here namespace denotes that serivceAccount is present is default namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
