apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    webapp: frontend
spec:
  type: NodePort
  selector:
    name: simple-webapp
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: 8080