apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      ram: shyam
  template:
    metadata:
      name: rtd
      labels:
        ram: shyam
    spec:
      containers:
        - name: rtdf
          image: registry.k8s.io/fluentd-elasticsearch:1.20
          
    