apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abhishek-roleBinding
  namespace: kube-system
subjects:
- kind: User
  name: abhishek
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: abhishek-role
  apiGroup: rbac.authorization.k8s.io
