apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: abhishek-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch","update"]
    