apiVersion: apps/v1
kind: Deployment
metadata:
  name: Red
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                    
    